/*
Copyright © 2023 NAME HERE <EMAIL ADDRESS>

*/
package add

import (
	"errors"
	"fmt"
	"os"

	"github.com/manifoldco/promptui"
	"github.com/spf13/cobra"

	"github.com/davidtaing/scriptcli/internal/editor"
	"github.com/davidtaing/scriptcli/internal/promptutil"
)

var (
	scriptName = "helloworld"
	scriptDir  = "bin"
)

var AddCmd = &cobra.Command{
	Use:   "add",
	Short: "A brief description of your command",
	Run: func(cmd *cobra.Command, args []string) {
		var err error
		if scriptName == "" {
			scriptName, err = promptScriptName()
		}

		if err != nil {
			fmt.Println(err)
			return
		}

		path, _ := createScript(scriptName)

		var openEditor = promptutil.PromptOpenEditor()

		if !openEditor {
			fmt.Println("Exiting")
		}

		if Editor == "" {
			Editor = promptutil.PromptSelectEditor()
		}

		editor.OpenScriptInEditor(path, Editor)
	},
}

func init() {
	AddCmd.Flags().StringVarP(&scriptName, "script", "s", "", "script file name")
}

func promptScriptName() (string, error) {
	var result string
	var err error

	p := promptui.Prompt{
		Label: "What would you like to name your new script?",
	}

	result, err = p.Run()

	if err != nil {
		fmt.Printf("Prompt failed %v\n", err)
		return "", err
	}

	if result == "" {
		return "", errors.New("New script name was not provided. Exiting")
	}

	return result, nil
}

func createScript(name string) (string, error) {
	var path = getScriptPath(scriptDir, name)

	err := os.WriteFile(path, []byte(`#!/bin/bash
echo "This Script was generated by Script CLI"`), 0755)

	if err != nil {
		fmt.Println("Error creating new script:", err)
		return "", err
	}

	fmt.Println("Created new script at", path)

	return path, nil
}

func getScriptPath(dirpath string, name string) string {
	return fmt.Sprintf("%s/%s.sh", dirpath, scriptName)
}
